name: 'Chkk Kubernetes Manifests'
description: 'Check your Kubernetes manifests for reliability risks'
inputs:
  kubernetes-manifest:
    description: 'Kubernetes manifest to check'
    required: true
  skip-checks:
    description: 'List of checks to skip'
    required: false
    default: "default"
  run-checks:
    description: 'List of checks to run'
    required: false
    default: "default"
  standalone-mode:
    description: 'Use Chkk Standalone Mode'
    required: false
    default: "false"
  args:
    description: 'Additional arguments to pass to Chkk'
    required: false

runs:
  using: "composite"
  steps:
    - run: VERSION=$(curl -sS https://get.chkk.dev/cli/latest.txt) && curl -Lo chkk https://get.chkk.dev/${VERSION}/chkk-linux-amd64
      shell: sh
    - run: chmod +x chkk
      shell: sh
    - run: if [ ${{ inputs.standalone-mode }} = true ]; then ./chkk standalone install; fi
      shell: sh
    - run: ./chkk -f ${{ inputs.kubernetes-manifest }} -s ${{ inputs.skip-checks }} -r ${{ inputs.enable-checks }} ${{ inputs.args }}
      shell: sh
